name: build
on:
  schedule:
    - cron: '0 0 * * 0' 
  push:
    branches:
      - master
      - main

env: # Change this if needed
  quarto_file: published-202312-cleynen-local
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  computorticle:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Installing dependencies with Micromamba
        uses: mamba-org/provision-with-micromamba@v14
        with:
          cache-env: true

      - name: Installing quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
          version: pre-release

      - name: Install Computo extension for Quarto
        run: |
            quarto add --no-prompt computorg/computo-quarto-extension

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Installing dependencies
        shell: bash -l {0}
        run: |
            Rscript r-addons.R

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
